import '../services/app_settings_service.dart';

class AppText {
  static String get(String key) {
    final lang = AppSettingsService.instance.languageCode;
    return _strings[lang]?[key] ?? _strings['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'home': 'Home',
      'services': 'Services',
      'profile': 'Profile',
      'core_modules': 'Core Modules',
      'today_snapshot': "Today's Situation",
      'today_tasks': 'Tasks for Today',
      'weather': 'Weather',
      'crops': 'Crops',
      'market': 'Market',
      'schemes': 'Schemes',
      'save_profile': 'Save Profile',
      'logout': 'Logout',
      'language': 'Language',
      'farmer_profile': 'Farmer Profile',
      'village_preferences': 'Farmer details and saved preferences',
      'preferred_crops': 'Preferred Crops',
      'saved_schemes': 'Saved Schemes',
      'about': 'About',
      'about_title': 'About Krishi Saarathi',
      'about_desc':
          'Krishi Saarathi helps farmers with weather guidance, crop planning, market support, and government schemes in one place.',
      'about_short': 'Know about this app',
      'hero_subtitle': 'Simple digital help for better farming decisions.',
      'greeting_title': 'Namaste, Farmer',
      'greeting_subtitle': 'Your smart assistant for weather, crops and prices.',
      'search_home_hint': 'Ask about soil, crops, pests...',
      'search_title': 'Farmer Help Search',
      'search_empty': 'Search soil, crop, pest, irrigation or market doubts.',
      'search_no_results':
          'No matching help found. Try soil, crop, pest, irrigation or market.',
      'search_note': 'Use this for quick farmer guidance and common doubts.',
      'badge_weather': 'Weather Support',
      'badge_crops': 'Crop Planning',
      'badge_market': 'Price Help',
      'home_weather_loading': "Loading today's weather...",
      'home_weather_unavailable': "Today's weather update is unavailable right now.",
      'weather_rainy': 'Today may be rainy or showery.',
      'weather_hot': 'Today looks hot.',
      'weather_mild': 'Today looks mild to partly cloudy.',
      'weather_normal': 'Today looks generally normal.',
      'advisory_rainy':
          'Check rain conditions before spraying and avoid extra irrigation.',
      'advisory_hot': 'Prefer irrigation in the morning or evening.',
      'advisory_normal':
          'Continue normal field work after checking soil moisture.',
      'home_market_tip': 'Check mandi prices before taking produce for sale.',
      'home_scheme_tip': 'Review useful schemes before buying seeds or inputs.',
      'task_forecast': 'Review the next 5-day rainfall forecast.',
      'task_field': 'Check the field for pest signs or leaf damage.',
      'task_market': 'Compare mandi rates before transport.',
      'phone_number': 'Phone Number',
      'guest_mode': 'Guest / desktop mode',
      'farmer_name': 'Farmer Name',
      'village_location': 'Village / Location',
      'profile_saved': 'Profile saved',
      'saved_schemes_hint': 'Saved scheme bookmarks can be shown here next.',
      'who_is_this_for': 'Who is this app for?',
      'who_is_this_for_desc':
          'Farmers, rural users, and anyone seeking agricultural support.',
      'main_purpose': 'Main purpose',
      'main_purpose_desc':
          'One place for weather, crop planning, market prices, and schemes.',
      'refresh': 'Refresh',
      'weather_screen_title': 'Weather Intelligence',
      'weather_search_label': 'Search village, town, district',
      'weather_search_hint': 'e.g. Pusa, Baramati, Adilabad',
      'forecast_5day': '5-Day Forecast',
      'temperature_short': 'Temp',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'rain': 'Rain',
      'weather_error': 'Unable to load weather details.',
      'season': 'Season',
      'soil_type': 'Soil Type',
      'water_availability': 'Water Availability',
      'main_goal': 'Main Goal',
      'best_fit_farm': 'Best Fit for Your Farm',
      'duration': 'Duration',
      'water': 'Water',
      'sowing': 'Sowing',
      'days': 'days',
      'fertilizer_tip': 'Fertilizer Tip',
      'risk_watch': 'Risk Watch',
      'market_outlook': 'Market Outlook',
      'kharif': 'Kharif',
      'rabi': 'Rabi',
      'zaid': 'Zaid',
      'loamy': 'Loamy',
      'clay': 'Clay',
      'sandy': 'Sandy',
      'black': 'Black',
      'alluvial': 'Alluvial',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'profit': 'Profit',
      'low_risk': 'Low Risk',
      'fast_harvest': 'Fast Harvest',
      'filter_state': 'State',
      'filter_commodity': 'Commodity',
      'all': 'All',
      'search_market_hint': 'Search commodity / market / district',
      'live_price_records': 'Live Price Records',
      'no_market_opportunities':
          'No market opportunities found for the selected filters.',
      'no_market_insight':
          'No market insight is available for the current filters.',
      'modal_price': 'Modal price',
      'min': 'Min',
      'modal': 'Modal',
      'max': 'Max',
      'schemes_screen_title': 'Government Schemes',
      'search_scheme_hint': 'Search scheme name or keyword',
      'live_schemes_count': 'live schemes',
      'source_india': 'Source: india.gov.in',
      'no_schemes_found': 'No schemes found.',
      'general': 'General',
      'ministry': 'Ministry',
      'description_unavailable': 'Description unavailable from source.',
      'weather_clear': 'Clear',
      'weather_mainly_clear': 'Mainly Clear',
      'weather_partly_cloudy': 'Partly Cloudy',
      'weather_overcast': 'Overcast',
      'weather_fog': 'Fog',
      'weather_drizzle': 'Drizzle',
      'weather_rain_label': 'Rain',
      'weather_showers': 'Showers',
      'weather_snow': 'Snow',
      'weather_thunderstorm': 'Thunderstorm',
      'weather_unknown': 'Weather Update',
    },
    'te': {
      'home': 'హోమ్',
      'services': 'సేవలు',
      'profile': 'ప్రొఫైల్',
      'core_modules': 'ముఖ్య భాగాలు',
      'today_snapshot': 'ఈ రోజు పరిస్థితి',
      'today_tasks': 'ఈ రోజు పనులు',
      'weather': 'వాతావరణం',
      'crops': 'పంటలు',
      'market': 'మార్కెట్',
      'schemes': 'పథకాలు',
      'save_profile': 'ప్రొఫైల్ సేవ్ చేయి',
      'logout': 'లాగ్ అవుట్',
      'language': 'భాష',
      'farmer_profile': 'రైతు ప్రొఫైల్',
      'village_preferences': 'రైతు వివరాలు మరియు సేవ్ చేసిన అభిరుచులు',
      'preferred_crops': 'ఇష్టమైన పంటలు',
      'saved_schemes': 'సేవ్ చేసిన పథకాలు',
      'about': 'గురించి',
      'about_title': 'కృషి సారథి గురించి',
      'about_desc':
          'కృషి సారథి యాప్ రైతులకు వాతావరణం, పంట ప్రణాళిక, మార్కెట్ సహాయం, మరియు ప్రభుత్వ పథకాల సమాచారం ఒకేచోట అందిస్తుంది.',
      'about_short': 'ఈ యాప్ గురించి తెలుసుకోండి',
      'hero_subtitle': 'మంచి వ్యవసాయ నిర్ణయాలకు సరళమైన డిజిటల్ సహాయం.',
      'greeting_title': 'నమస్తే రైతు',
      'greeting_subtitle': 'వాతావరణం, పంటలు మరియు ధరల కోసం మీ సహాయక యాప్.',
      'search_home_hint': 'మట్టి, పంట, పురుగు సందేహాలు వెతకండి...',
      'search_title': 'రైతు సహాయం వెతకండి',
      'search_empty': 'మట్టి, పంట, పురుగు, నీరు లేదా మార్కెట్ సందేహాలు వెతకండి.',
      'search_no_results':
          'సరిపోయే సమాచారం దొరకలేదు. మట్టి, పంట, పురుగు, నీరు లేదా మార్కెట్ అని ప్రయత్నించండి.',
      'search_note': 'ఇది రైతుల సాధారణ సందేహాలకు త్వరిత సహాయం కోసం.',
      'badge_weather': 'వాతావరణ సహాయం',
      'badge_crops': 'పంట ప్రణాళిక',
      'badge_market': 'ధర సహాయం',
      'home_weather_loading': 'ఈ రోజు వాతావరణం లోడ్ అవుతోంది...',
      'home_weather_unavailable':
          'ఈ రోజు వాతావరణ సమాచారం ప్రస్తుతం అందుబాటులో లేదు.',
      'weather_rainy': 'ఈ రోజు వర్షం లేదా జల్లులు ఉండే అవకాశం ఉంది.',
      'weather_hot': 'ఈ రోజు వేడిగా ఉండే అవకాశం ఉంది.',
      'weather_mild': 'ఈ రోజు తేలికైన మేఘావృతం లేదా సాధారణ వాతావరణం ఉంటుంది.',
      'weather_normal': 'ఈ రోజు వాతావరణం సాధారణంగా ఉంటుంది.',
      'advisory_rainy':
          'స్ప్రే చేయడానికి ముందు వర్ష పరిస్థితి చూడండి, అదనపు నీరు అవసరం లేకపోవచ్చు.',
      'advisory_hot': 'ఉదయం లేదా సాయంత్రం నీరు ఇవ్వడం మంచిది.',
      'advisory_normal':
          'నేల తేమను చూసుకుని సాధారణ వ్యవసాయ పనులు కొనసాగించండి.',
      'home_market_tip': 'ఉత్పత్తి అమ్మకానికి ముందు మార్కెట్ ధరలు చూసుకోండి.',
      'home_scheme_tip':
          'విత్తనాలు లేదా ఇన్‌పుట్లు కొనుగోలు చేసే ముందు ఉపయోగకరమైన పథకాలు చూడండి.',
      'task_forecast': 'తదుపరి 5 రోజుల వర్ష సూచనను పరిశీలించండి.',
      'task_field': 'పొలంలో పురుగు లేదా ఆకుల నష్టం ఉన్నదేమో చూడండి.',
      'task_market': 'రవాణా ముందు మార్కెట్ ధరలను పోల్చండి.',
      'phone_number': 'ఫోన్ నంబర్',
      'guest_mode': 'గెస్ట్ / డెస్క్‌టాప్ మోడ్',
      'farmer_name': 'రైతు పేరు',
      'village_location': 'గ్రామం / ప్రాంతం',
      'profile_saved': 'ప్రొఫైల్ సేవ్ అయింది',
      'saved_schemes_hint': 'తరువాత సేవ్ చేసిన పథకాలను ఇక్కడ చూపించవచ్చు.',
      'who_is_this_for': 'ఈ యాప్ ఎవరికోసం?',
      'who_is_this_for_desc':
          'రైతులు, గ్రామీణ వినియోగదారులు, మరియు వ్యవసాయ సహాయం కోరేవారికి.',
      'main_purpose': 'ప్రధాన ఉపయోగం',
      'main_purpose_desc':
          'వాతావరణం, పంట ప్రణాళిక, మార్కెట్ ధరలు, మరియు పథకాలకు ఒకే చోట సహాయం.',
      'refresh': 'రిఫ్రెష్',
      'weather_screen_title': 'వాతావరణ సమాచారం',
      'weather_search_label': 'గ్రామం, పట్టణం, జిల్లా వెతకండి',
      'weather_search_hint': 'ఉదా: పూసా, బారామతి, ఆదిలాబాద్',
      'forecast_5day': '5 రోజుల సూచన',
      'temperature_short': 'ఉష్ణోగ్రత',
      'humidity': 'తేమ',
      'wind': 'గాలి',
      'rain': 'వర్షం',
      'weather_error': 'వాతావరణ వివరాలు లోడ్ కాలేదు.',
      'season': 'సీజన్',
      'soil_type': 'మట్టి రకం',
      'water_availability': 'నీటి లభ్యత',
      'main_goal': 'ప్రధాన లక్ష్యం',
      'best_fit_farm': 'మీ పొలానికి సరిపోయే పంట',
      'duration': 'కాలం',
      'water': 'నీరు',
      'sowing': 'విత్తే సమయం',
      'days': 'రోజులు',
      'fertilizer_tip': 'ఎరువు సూచన',
      'risk_watch': 'జాగ్రత్త',
      'market_outlook': 'అమ్మకపు అవకాశం',
      'kharif': 'ఖరీఫ్',
      'rabi': 'రబీ',
      'zaid': 'జైద్',
      'loamy': 'లోమీ',
      'clay': 'మట్టి',
      'sandy': 'ఇసుక మట్టి',
      'black': 'నల్ల మట్టి',
      'alluvial': 'అల్యూవియల్',
      'low': 'తక్కువ',
      'medium': 'మధ్యస్థం',
      'high': 'ఎక్కువ',
      'profit': 'లాభం',
      'low_risk': 'తక్కువ ప్రమాదం',
      'fast_harvest': 'త్వరిత కోత',
      'filter_state': 'రాష్ట్రం',
      'filter_commodity': 'పంట',
      'all': 'అన్ని',
      'search_market_hint': 'పంట / మార్కెట్ / జిల్లా వెతకండి',
      'live_price_records': 'ప్రత్యక్ష ధర రికార్డులు',
      'no_market_opportunities':
          'ఎంచుకున్న ఫిల్టర్లకు సరిపోయే మార్కెట్ అవకాశాలు లేవు.',
      'no_market_insight': 'ప్రస్తుత ఫిల్టర్లకు ధర సమాచారం అందుబాటులో లేదు.',
      'modal_price': 'మోడల్ ధర',
      'min': 'కనిష్టం',
      'modal': 'మధ్య ధర',
      'max': 'గరిష్టం',
      'schemes_screen_title': 'ప్రభుత్వ పథకాలు',
      'search_scheme_hint': 'పథకం పేరు లేదా కీలక పదం వెతకండి',
      'live_schemes_count': 'ప్రత్యక్ష పథకాలు',
      'source_india': 'మూలం: india.gov.in',
      'no_schemes_found': 'పథకాలు లభించలేదు.',
      'general': 'సాధారణం',
      'ministry': 'మంత్రిత్వ శాఖ',
      'description_unavailable': 'మూల వనరులో వివరణ అందుబాటులో లేదు.',
      'weather_clear': 'స్పష్టమైన వాతావరణం',
      'weather_mainly_clear': 'ముఖ్యంగా స్వచ్ఛమైన ఆకాశం',
      'weather_partly_cloudy': 'పాక్షిక మేఘావృతం',
      'weather_overcast': 'మేఘావృతం',
      'weather_fog': 'మంచు / పొగమంచు',
      'weather_drizzle': 'చినుకులు',
      'weather_rain_label': 'వర్షం',
      'weather_showers': 'జల్లులు',
      'weather_snow': 'మంచు',
      'weather_thunderstorm': 'ఉరుములతో వర్షం',
      'weather_unknown': 'వాతావరణ సమాచారం',
    },
  };
}
